# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30fe9e7bb963d411cf7b07f295fc2ef6e6b9ac4d07885c72a114f3852a16fbb0e74d1b26650784ecf440e28ad47a0538598f2dc2cb0f7e4e57a2a93219c6e234

test:
  secret_key_base: 29708428ec1a2be38e7c51dbbd3550a7447e78af380bf91895afaaa3863e5d3c5514b3872c7a6b570bb52529cec777f7b8961b3bf0c519656e9f15f0622bb2b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
